In [5]:
import pandas as pd
import json

In [11]:
df = pd.read_json("data.json")

In [12]:
df

                                             social_D                                            price_D
0   {'cumulative_z': 0.0, '90day_bull_prop': 0.573...  {'volume': 23473223, 'daily_average_volume_30'...
1   {'cumulative_z': 0.6785988411155951, '90day_bu...  {'volume': 20728639, 'daily_average_volume_30'...
2   {'cumulative_z': 3.227714534600114, '90day_bul...  {'volume': 20687588, 'daily_average_volume_30'...
3   {'cumulative_z': 0.322420014304218, '90day_bul...  {'volume': 21405057, 'daily_average_volume_30'...
4   {'cumulative_z': 0.0, '90day_bull_prop': 0.578...  {'volume': 20151228, 'daily_average_volume_30'...
5   {'cumulative_z': 1.821654151536401, '90day_bul...  {'volume': 23159789, 'daily_average_volume_30'...
6   {'cumulative_z': 0.0, '90day_bull_prop': 0.580...  {'volume': 36145213, 'daily_average_volume_30'...
7   {'cumulative_z': 0.62374586807664, '90day_bull...  {'volume': 26148352, 'daily_average_volume_30'...
8   {'cumulative_z': 0.0, '90day_bull_prop': 0.583...  {'volume': 21042972, 'daily_average_volume_30'...
9   {'cumulative_z': 0.8533815523121391, '90day_bu...  {'volume': 21120300, 'daily_average_volume_30'...
10  {'cumulative_z': 0.187556518192108, '90day_bul...  {'volume': 17095740, 'daily_average_volume_30'...
11  {'cumulative_z': 1.267602840339656, '90day_bul...  {'volume': 18650190, 'daily_average_volume_30'...
12  {'cumulative_z': 0.0, '90day_bull_prop': 0.588...  {'volume': 21887046, 'daily_average_volume_30'...
13  {'cumulative_z': 1.561853278353647, '90day_bul...  {'volume': 19446031, 'daily_average_volume_30'...
14  {'cumulative_z': 0.9626828409037681, '90day_bu...  {'volume': 17028428, 'daily_average_volume_30'...
15  {'cumulative_z': 0.836296102841481, '90day_bul...  {'volume': 15165846, 'daily_average_volume_30'...
16  {'cumulative_z': 0.0, '90day_bull_prop': 0.599...  {'volume': 24733998, 'daily_average_volume_30'...
17  {'cumulative_z': 2.034662620140833, '90day_bul...  {'volume': 19129084, 'daily_average_volume_30'...
18  {'cumulative_z': 0.9605992778770831, '90day_bu...  {'volume': 19044879, 'daily_average_volume_30'...
19  {'cumulative_z': 0.36283385965400605, '90day_b...  {'volume': 12433057, 'daily_average_volume_30'...
20  {'cumulative_z': 0.34040310049035105, '90day_b...  {'volume': 28934836, 'daily_average_volume_30'...
21  {'cumulative_z': 0.563049286294375, '90day_bul...  {'volume': 9120289, 'daily_average_volume_30':...
22  {'cumulative_z': 0.524671292659592, '90day_bul...  {'volume': 20178517, 'daily_average_volume_30'...
23  {'cumulative_z': 0.556943394699082, '90day_bul...  {'volume': 17624265, 'daily_average_volume_30'...
24  {'cumulative_z': 0.005250586963619, '90day_bul...  {'volume': 17822880, 'daily_average_volume_30'...
25  {'cumulative_z': 0.24902027997313703, '90day_b...  {'volume': 16386194, 'daily_average_volume_30'...
26  {'cumulative_z': 0.0, '90day_bull_prop': 0.600...  {'volume': 14648740, 'daily_average_volume_30'...
27  {'cumulative_z': 0.199988446712932, '90day_bul...  {'volume': 17251129, 'daily_average_volume_30'...
28  {'cumulative_z': 0.0, '90day_bull_prop': 0.599...  {'volume': 23237384, 'daily_average_volume_30'...
29  {'cumulative_z': 0.0, '90day_bull_prop': 0.598...  {'volume': 17155356, 'daily_average_volume_30'...
30  {'cumulative_z': 0.0, '90day_bull_prop': 0.608...  {'volume': 16817303, 'daily_average_volume_30'...
31  {'cumulative_z': 0.0, '90day_bull_prop': 0.606...  {'volume': 14648351, 'daily_average_volume_30'...
32  {'cumulative_z': 0.6828887945025951, '90day_bu...  {'volume': 19730753, 'daily_average_volume_30'...
33  {'cumulative_z': 0.260577072962525, '90day_bul...  {'volume': 14048345, 'daily_average_volume_30'...
34  {'cumulative_z': 2.042332323116807, '90day_bul...  {'volume': 9643103, 'daily_average_volume_30':...
35  {'cumulative_z': 2.792605714366492, '90day_bul...  {'volume': 33412756, 'daily_average_volume_30'...
36  {'cumulative_z': 4.462860347685502, '90day_bul...  {'volume': 40156574, 'daily_average_volume_30'...
37  {'cumulative_z': 3.216427486462948, '90day_bul...  {'volume': 45310198, 'daily_average_volume_30'...
38  {'cumulative_z': 1.212007287578328, '90day_bul...  {'volume': 23300620, 'daily_average_volume_30'...
39  {'cumulative_z': 0.068691935762849, '90day_bul...  {'volume': 26729098, 'daily_average_volume_30'...
40  {'cumulative_z': 2.084473114264399, '90day_bul...  {'volume': 48415734, 'daily_average_volume_30'...
41  {'cumulative_z': 1.83277819835123, '90day_bull...  {'volume': 37647336, 'daily_average_volume_30'...
42  {'cumulative_z': 1.9046084932357, '90day_bull_...  {'volume': 25716462, 'daily_average_volume_30'...
43  {'cumulative_z': 1.075591683841573, '90day_bul...  {'volume': 26147683, 'daily_average_volume_30'...
44  {'cumulative_z': 4.217584572018003, '90day_bul...  {'volume': 32171986, 'daily_average_volume_30'...
45  {'cumulative_z': 0.7949786338593671, '90day_bu...  {'volume': 25937589, 'daily_average_volume_30'...
46  {'period_abs': 0, 'cumulative_z': 0, '90day_bu...  {'volume': 19950239, 'daily_average_volume_30'...
47  {'period_abs': 0, 'cumulative_z': 0, '90day_bu...  {'volume': 49538558, 'daily_average_volume_30'...
48  {'period_abs': 0, 'cumulative_z': 0, '90day_bu...  {'volume': 33342446, 'daily_average_volume_30'...
49  {'period_abs': 0, 'cumulative_z': 0, '90day_bu...  {'volume': 26816191, 'daily_average_volume_30'...

In [46]:
social_D_90_day= []
social_D_cum_abs = []
cum_z = []

price_D_volume = []
price_D_last = []
date = []



for i in range(0,len(df)):
    social_D_90_day.append(df['social_D'][i]['90day_bull_prop_rollingz_60'])
    social_D_cum_abs.append(df['social_D'][i]['cumulative_abs'])

    price_D_volume.append(df['price_D'][i]['volume'])
    price_D_last.append(df['price_D'][i]['last'])
    date.append(df['price_D'][i]['date'])
    
    cum_z.append(df['social_D'][i]['cumulative_z'])

print("Minimum 90day_bull_prop_rollingz_60 in social_D is " + str(min(social_D_90_day)))
print("Maximum 90day_bull_prop_rollingz_60 in social_D is " + str(max(social_D_90_day)))
print("Avg 90day_bull_prop_rollingz_60 in social_D is " + str(sum(social_D_90_day)/len(df)))
print("===========================================")
print("Minimum cumulative_abs in social_D is " + str(min(social_D_cum_abs)))
print("Maximum cumulative_abs in social_D is " + str(max(social_D_cum_abs)))
print("Avg cumulative_abs in social_D is " + str(sum(social_D_cum_abs)/len(df)))
print("===========================================")
print("Minimum volume in price_D is " + str(min(price_D_volume)))
print("Maximum volume in price_D is " + str(max(price_D_volume)))
print("Avg volume in price_D is " + str(sum(price_D_volume)/len(df)))
print("===========================================")
print("Minimum last in price_D is " + str(min(price_D_last)))
print("Maximum last in price_D is " + str(max(price_D_last)))
print("Avg last in price_D is " + str(sum(price_D_last)/len(df)))

Minimum 90day_bull_prop_rollingz_60 in social_D is 0.667930897289374
Maximum 90day_bull_prop_rollingz_60 in social_D is 2.211399544341178
Avg 90day_bull_prop_rollingz_60 in social_D is 1.1638202636558288
===========================================
Minimum cumulative_abs in social_D is 0
Maximum cumulative_abs in social_D is 2174
Avg cumulative_abs in social_D is 743.32
===========================================
Minimum volume in price_D is 9120289
Maximum volume in price_D is 49538558
Avg volume in price_D is 23410351.5
===========================================
Minimum last in price_D is 136.53
Maximum last in price_D is 156.1
Avg last in price_D is 143.66100000000003

In [31]:
import numpy as np

sorted_index = np.argsort(price_D_last)

In [32]:
sorted_index

array([ 2,  3,  0,  4,  5,  1, 12,  7, 15, 11, 13, 14,  9, 10,  8,  6, 20,
       16, 21, 17, 27, 18, 19, 24, 23, 26, 22, 25, 29, 28, 30, 32, 33, 34,
       31, 38, 35, 37, 36, 39, 47, 48, 49, 40, 42, 43, 41, 46, 45, 44])

In [35]:
for i in range(0,3):
    print("Date: " + str(date[sorted_index[i]]))
    print("Price: " + str(price_D_last[sorted_index[i]]))
    print("-----------------------------------")

Date: 2017-02-23
Price: 136.53
-----------------------------------
Date: 2017-02-24
Price: 136.66
-----------------------------------
Date: 2017-02-21
Price: 136.7
-----------------------------------

In [47]:
df_new = pd.DataFrame(zip(date,social_D_90_day,cum_z,price_D_last), columns = ['date', '90day_bull_prop_rollingz_60', 'cumulative_z', 'last'])

In [48]:
df_new.head()

         date  90day_bull_prop_rollingz_60  cumulative_z    last
0  2017-02-21                     1.165598      0.000000  136.70
1  2017-02-22                     1.131646      0.678599  137.07
2  2017-02-23                     1.125000      3.227715  136.53
3  2017-02-24                     1.087875      0.322420  136.66
4  2017-02-27                     1.065403      0.000000  136.93

In [49]:
df_new.to_csv("data.csv")